# Import required libraries and packages
import os
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration

# Load model and pre-processor
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large").to("cuda")

def generate_caption(image) -> str :
    """
    image: path to image file
    return: caption generated by the model
    """

    raw_image = Image.open(image).convert('RGB')    
    inputs = processor(raw_image, return_tensors="pt").to("cuda")    
    out = model.generate(**inputs)
    raw_image.show()
    print(processor.decode(out[0], skip_special_tokens=True))

images = os.listdir(os.path.join(os.getcwd(), 'images'))

for img in images:
    image = os.path.join(os.getcwd(), 'images', img)
    generate_caption(image)